package com.myjava.service.domain;

import java.io.Serializable;

public class MyUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_user.id
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_user.name
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_user.phone
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_user.telephone
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_user.address
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_user.enabled
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_user.username
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_user.password
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_user.userface
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    private String userface;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_user.remark
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table my_user
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_user
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    public MyUser(Integer id, String name, String phone, String telephone, String address, Boolean enabled, String username, String password, String userface, String remark) {
        this.id = id;
        this.name = name;
        this.phone = phone;
        this.telephone = telephone;
        this.address = address;
        this.enabled = enabled;
        this.username = username;
        this.password = password;
        this.userface = userface;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.id
     *
     * @return the value of my_user.id
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.name
     *
     * @return the value of my_user.name
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.phone
     *
     * @return the value of my_user.phone
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.telephone
     *
     * @return the value of my_user.telephone
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.address
     *
     * @return the value of my_user.address
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.enabled
     *
     * @return the value of my_user.enabled
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.username
     *
     * @return the value of my_user.username
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.password
     *
     * @return the value of my_user.password
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.userface
     *
     * @return the value of my_user.userface
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    public String getUserface() {
        return userface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.remark
     *
     * @return the value of my_user.remark
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    public String getRemark() {
        return remark;
    }
}