package com.myjava.dao;

import com.myjava.domain.MyUser;
import com.myjava.domain.MyUserExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface MyUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_user
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    int countByExample(MyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_user
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    int deleteByExample(MyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_user
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_user
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    int insert(MyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_user
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    int insertSelective(MyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_user
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    List<MyUser> selectByExample(MyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_user
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    MyUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_user
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") MyUser record, @Param("example") MyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_user
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    int updateByExample(@Param("record") MyUser record, @Param("example") MyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_user
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    int updateByPrimaryKeySelective(MyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_user
     *
     * @mbggenerated Fri May 22 10:09:28 CST 2020
     */
    int updateByPrimaryKey(MyUser record);
}